### ISSUE TITLE
Add deselect all button to Selected Reports pane

### ISSUE THREAD

**Issue by peltonc** [AASHE/bt#147] opened 2018-09-21 12:41 UTC
I may be missing something, but I can't figure out a simple way to compare an institution against an large aggregated group of which it is a member. For example, if I form a group of all Bronze institutions, all Bronze institutions remain selected. To compare a single Bronze institution to the aggregated group, I have to deselect, one at a time, all the institutions but the one I'm interested in. I think a "Deselect All" button would make things much easier.

**Comment by dodget** [comment] 2018-09-21 12:44
Agreed! Is this a dupe of #36 ?

**Comment by peltonc** [comment] 2018-09-21 12:57
Ah, I believe it is. Searched for "deselect" rather than "remove".

**Comment by dodget** [comment] 2018-09-21 19:45
Ok, I'll close in favor of the original.

**Closed by dodget** 2018-09-21 19:45 UTC
Labels: enhancement
