### ISSUE TITLE
Enhance mobile support

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#18] opened 2018-04-22 16:03 UTC
Fully test on mobile.

**Comment by jamstooks** [comment] 2018-05-01 15:53
- [ ] Graphs should use click, instead of mouse-over for pop-up box details.

**Comment by peltonc** [comment] 2018-05-01 16:12
Crystal raises a good point about the orientation of the search filter and data filter buttons. I wonder if locating them together would be more mobile-friendly.

**Comment by jamstooks** [comment] 2018-05-01 16:15
I personally like the positions, as they tie in to the axes of the graph, but we can definitely discuss this.

**Comment by jamstooks** [comment] 2018-07-13 15:51
Look into reported scrolling issues.

**Comment by juliandsmith** [comment] 2018-07-31 16:57
All I see when I open the URL in Chrome on my Android is the faded STARS swoosh. I don't see any text or menu buttons, even if I try to scroll around.

**Comment by dodget** [comment] 2018-10-18 13:51
Login and about page have been optimized for mobile. Moving to landing page.

**Comment by dodget** [comment] 2018-10-19 19:39
Closing this issue. After recent work, mobile is more clearly supported, and the issue is overly vague. Please, open a new issue with specific request if needed.

**Closed by dodget** 2018-10-19 19:39 UTC
Labels: for discussion
