### ISSUE TITLE
Saving doesn't work for large datasets

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#225] opened 2019-02-15 19:38 UTC
I discovered that saving a benchmark with a large number of institutions seems to fail. I tried to save several benchmarks with all 171 research institutions. Although I didn't receive any error message and everything proceeded as normal during the saving process, they never showed up in my list of saved benchmarks. I tried a few different times to make sure I just wasn't doing something wrong. I assume it is a size issue because I was able to successfully save several benchmarks with smaller numbers of institutions.

As a side note, it's kind of a pain that saving a benchmark doesn't generate a shareable link right away - I have to go back to the landing page to see if it saved properly and to get the link. If I didn't open the landing page in a new tab, this also means I lose the benchmark I was working on and have to recreate it from scratch, which is pretty frustrating.

**Comment by dodget** [comment] 2019-02-15 19:48
Interesting.

Regarding the side note:
We need the benchmark to be saved before we can generate a link. The end part of the URL that of the public view of a benchmark is a unique key. Because it is required to be unique, we need collision detection in the database, which is a backend procedure.

Also, you can select the `Take me back` button to reload the benchmark you were working on, rather that clicking New Benchmark. It's located next to the `Toggle View` button under "Your Benchmarks"

**Comment by dodget** [comment] 2019-02-19 23:52
I just finished up some bug squashing in STARS and now I'm here. I'm checking over the logs, and it looks like there is a `DATA_UPLOAD_MAX_MEMORY_SIZE` coming from heroku that we are hitting up against. Makes sense why it's unreproducible locally. Hopefully this will be a swift fix.

**Comment by dodget** [comment] 2019-02-20 01:06
Ok, I've doubled the max-upload amount, and large data sets are saving. I could remove the limit entirely, but that brings security concerns with it. I can leave this ticket open if we should discuss what is a reasonable limit, if the doubled amount is not suiting us.

**Comment by dodget** [comment] 2019-02-20 18:40
Ok, I'll close this issue now. If we are needing to increase the upload size further, I'd recommend that we pursue another avenue, but that would require some discussion about use-cases and security.

**Closed by dodget** 2019-02-20 18:40 UTC
Labels: bug
