### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by dodget** [AASHE/bt#57] opened 2018-07-11 18:48 UTC
Create a landing page for the application

**Comment by dodget** [comment] 2018-07-11 19:11
@jamstooks - I've done a very basic integration between the landing page and the benchmarking tool in the 'landing-page' branch. There is a bit of cleanup there that I will get to this week. I am going to start on adding bookmarks to the backend tomorrow. I think we should call them 'benchmarks,' tough.

**Comment by jamstooks** [comment] 2018-07-14 04:57
is this a dupe of #39

**Comment by dodget** [comment] 2018-07-17 12:01
Yes, it is.

**Comment by jamstooks** [comment] 2018-07-20 20:31
Closing in favor of #39;

**Closed by jamstooks** 2018-07-20 20:31 UTC
